version: "3"

services:
  dynamodb-local:
    container_name: dynamodb-local
    image: amazon/dynamodb-local:1.17.0
    ports:
      - 8000:8000
    command: -jar DynamoDBLocal.jar -dbPath /data -sharedDb -optimizeDbBeforeStartup

    volumes:
      - ./resource/data:/data
    networks:
      - sam-local-tools
networks:
  sam-local-tools:
    driver: bridge
